--when.repositories = ["~/github/zenith"]

[user]
name = "Zenno Zenith"
email = "95485961+ZennoZenith@users.noreply.github.com"

[signing]
behavior = "own"
backend = "gpg"
# key = "1CDCB4568D6A0051"
key = "99DCA16E0E956F82"
