"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Zenno Zenith"
email = "95485961+ZennoZenith@users.noreply.github.com"

[git]
sign-on-push = true
subprocess = true

[signing]
behavior = "own"
backend = "gpg"
# key = "1CDCB4568D6A0051"
key = "99DCA16E0E956F82"

[ui]
default-command = ["log", "--limit", "6"]

# pager = ["delta", "--pager", "less -FRX"]
pager = ["delta", "-s", "--dark"]
diff-formatter = ":git"

diff-editor = ":builtin" 
# diff-editor = "meld" 

# # merge-editor = "meld"
# merge-editor = ["meld", "$left", "$base", "$right", "-o", "$output"]

# ## if `merge-editor = "meld"` above
# # [merge-tools.meld]
# # merge-args = ["$left", "$base", "$right", "-o", "$output", "--auto-merge"]

## If not using default pager(less)
[colors]
"diff removed token" = { fg = "bright red", bg = "#400000", underline = false }
"diff added token" = { fg = "bright green", bg = "#003000", underline = false }

[aliases]
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]
n = ["new"]
